repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: pretty-format-json
      - id: check-yaml
      - id: check-toml
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-added-large-files
        args: [ "--maxkb=5120" ]

      - id: detect-aws-credentials
        args: [ "--allow-missing-credentials" ]
      - id: detect-private-key

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      - id: hadolint
        args: [ "--failure-threshold=error" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
      - id: pyupgrade
        name: Upgrade code
        args: [ --py38-plus ]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        name: MD formatting
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

  - repo: local
    hooks:
      - id: update-requirements
        name: Update requirements
        entry: make create_requirements
        language: system
        files: pyproject.toml|poetry.lock
        pass_filenames: false

      - id: yesqa
        name: Unused noqa
        entry: yesqa
        language: system
        types: [ python ]

      - id: flake8
        name: wemake-python-styleguide
        entry: flake8
        language: system
        types: [ python ]

      - id: mypy
        name: Type checking
        entry: mypy --install-types --non-interactive custom_plotly_templates tests
        args: ["--scripts-are-modules"]
        pass_filenames: false
        language: system
        types: [ python ]

      - id: pytest
        name: Run tests
        entry: pytest
        pass_filenames: false
        language: system
        types: [ python ]
        stages: [ push ]

      - id: clean
        name: Remove unused files
        entry: make clean
        pass_filenames: false
        language: system
        stages: [ push ]
